require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*
    - db/**/*
    - config.ru
    - Capfile
    - Gemfile
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/users/registrations_controller.rb

Rails/Present:
  Exclude:
    - bin/bundle

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/ExampleLength:
  Max: 10

RSpec/ExpectActual:
  Exclude:
    - spec/routes_spec.rb

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
