require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec

AllCops:
  # Exclude:
  #   - db/schema.rb
  #   - node_modules/**/*
  #   - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*
    - db/**/*
    - config.ru
    - Gemfile
    - Rakefile

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Rails/Present:
  Exclude:
    - bin/bundle

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/ExpectActual:
  Exclude:
    - spec/routes_spec.rb
