default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: localhost
  username: dusic
  password: <%= Rails.application.credentials.db[:password] %>

development:
  <<: *default
  database: dusic_development
test:
  <<: *default
  database: dusic_test
production:
  <<: *default
  database: dusic_production
