name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.2']
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Load credentials key
      run: echo '${{ secrets.TEST_CREDENTIALS_KEY }}' > config/credentials/test.key
    - name: Install dependent libraries
      run: |
        sudo apt-get install libpq-dev
        yarn install
        bundle install
    - name: Setup Database
      run: |
        cp config/database.github-actions.yml config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    - name: Run webpack
      run: bundle exec rails webpacker:compile
      env:
        RAILS_ENV: test
    - name: Run rubocop
      run: bundle exec rake rubocop
    - name: Run rspec
      run: bundle exec rake spec
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
